import Footer from "../Footer/Footer";
import Navbar from "../Navbar/Navbar";
import ScrollToTop from "../Tools/ScrollToTop";
import { useState, useEffect } from "react";
import Head from "next/head";
import { motion } from "framer-motion";
export default function Layout({ children }) {
  const [components, setComponents] = useState(null);
  useEffect(() => {
    setTimeout(() => {
      const components = (
        <>
          <Navbar />
          {children}
          <ScrollToTop />
          <Footer />
        </>
      );
      setComponents(components);
    }, 1000);
  },[components]);
  return (
    <div className="content">
      <Head>
        <title>Boka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {components && <>{components}</>}
      {!components && (
        <motion.div
          animate={{ opacity: 1, scale: 1 }}
          initial={{ opacity: 0, scale: 0 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.5 }}
          layout
          className=" bg-white flex justify-center h-screen items-center"
        >
          <div className="loader">
            {[1, 2, 3, 4, 5, 6, 7].map((index) => (
              <div className="loader-square" key={index}></div>
            ))}
          </div>
        </motion.div>
      )}
    </div>
  );
}
